import type { Metadata } from "next";
import "./css/globals.css";
import GetFullYear from "@/components/get-full-year";
import Header from "@/components/_shared/header/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <Header />
        <main className="container mx-auto py-16 px-6">{children}</main>

        <footer className="text-gray-400 text-center text-xs">
          <p>
            CopyRight &copy; 2022 - <GetFullYear />
          </p>
        </footer>
      </body>
    </html>
  );
}
